# .github/workflows/cd.yml
name: 'Terraform CD'

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    name: 'Create Release Artifact'
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.get_version.outputs.new_version }}
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install semver tool'
        run: |
          wget -q -O /usr/local/bin/semver https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver
          chmod +x /usr/local/bin/semver

      - name: 'Get Version'
        id: get_version
        run: |
          last_version=$(git tag --sort=-version:refname | head -n1)
          if [ -z "$last_version" ]; then
            new_version="1.0.0"
          elif [[ "${{ github.event.head_commit.message }}" =~ ^major ]]; then
            new_version=$(semver bump major ${last_version#v})
          elif [[ "${{ github.event.head_commit.message }}" =~ ^feat ]]; then
            new_version=$(semver bump minor ${last_version#v})
          else
            new_version=$(semver bump patch ${last_version#v})
          fi
          echo "new_version=v$new_version" >> $GITHUB_OUTPUT
          echo "New version: v$new_version"

      - name: 'Build'
        run: zip -r prod-release-artifact.zip *.tf modules/
          
      - name: 'Release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          name: "Release ${{ steps.get_version.outputs.new_version }}"
          files: "prod-release-artifact.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload Artifact'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: 'Push to S3'
        run: aws s3 cp prod-release-artifact.zip s3://reetwiz-artifact/releases/${{ steps.get_version.outputs.new_version }}/prod-release-artifact.zip

      - name: 'Comment Artifact'
        uses: mschilde/add-pr-comment@v2
        with:
          message: |
            **Release Created**: ${{ steps.get_version.outputs.new_version }}
            **Artifact**: `prod-release-artifact.zip`
            **S3 Location**: `s3://reetwiz-artifact/releases/${{ steps.get_version.outputs.new_version }}/`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Summary'
        run: |
          echo "## Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: ${{ steps.get_version.outputs.new_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Artifact**: prod-release-artifact.zip" >> $GITHUB_STEP_SUMMARY
          echo "- **S3 Path**: s3://reetwiz-artifact/releases/${{ steps.get_version.outputs.new_version }}/" >> $GITHUB_STEP_SUMMARY